
  
# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.

undo_backspace: false
backend: Clipboard
fast_inject: true
toggle_key: OFF

matches:
  - trigger: "tutt"
    replace: "Hallo\nIst $|$ noch zu haben?\nFreundliche Grüsse\nSilas Schweizer"
    word: true

  - trigger: "NN"
    replace: "Silas Schweizer"
    case: true
    word: true

  - trigger: "rutil"
    replace: "source('~/kDrive/areas/personal/productivity/util.R')"
    word: true

  - trigger: "ueml"
    replace: "ssilas@student.ethz.ch"
    word: true

  - trigger: "eml"
    replace: "silas@ik.me"
    word: true

  - trigger: "hadr"
    replace: "Obere Reppischstrasse 13, 8953 Dietikon"
    word: true

  - trigger: "bnkre"
    replace: "5354569700670024"

  - trigger: "bnke"
    replace: "CH0580808007221521004"

  - trigger: "bnkf"
    replace: "CH8680808002608080624"

  - trigger: "ttn"
    replace: "0786859232"

  - trigger: "frgs"
    replace: "Freundliche Grüsse\nSilas Schweizer"

  - trigger: "mrgs"
    replace: "Merci und freundliche Grüsse\nSilas Schweizer"

  - trigger: "lgs"
    replace: "LG\nSilas"
    word: true

  - trigger: "ahvnr"
    replace: "756.5260.8190.50"

  - trigger: "krgs"
    replace: "Kind regards\nSilas Schweizer"

  - trigger: "w/"
    replace: "with"

  - trigger: "chs"
    replace: "Switzerland"
    word: true

  - trigger: "cant"
    replace: "can't"
    propagate_case: true
    word: true

  - trigger: "doesnt"
    replace: "doesn't"
    word: true
    propagate_case: true

  - trigger: "dont"
    replace: "don't"
    word: true
    propagate_case: true

  - trigger: "couldnt"
    replace: "could'nt"
    word: true
    propagate_case: true

  - trigger: "wont"
    replace: "won't"
    word: true  
    propagate_case: true

  - trigger: "hasnt"
    replace: "hasn't"
    word: true
    propagate_case: true

  - trigger: "chrs"
    replace: "Cheers\nSilas"
    word: true

  - trigger: "arent"
    replace: "aren't"
    propagate_case: true
   
# Dates
  - trigger: "ddate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  - trigger: "tz;"
    replace: " - trigger: \"$|$;\"\n replace: \"\""